[package]
name = "bubblegum"
version = "0.12.0"
description = "NFT Compression"
authors = ["Metaplex Developers <dev@metaplex.com>"]
repository = "https://github.com/metaplex-foundation/mpl-bubblegum"
license-file = "../../../LICENSE"
edition = "2021"
readme = "../README.md"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
test-sbf = []
default = []

[dependencies]
anchor-lang = { version = "0.29.0", features = ["init-if-needed"] }
anchor-spl = "0.29.0"
bytemuck = "1.13.0"
mpl-token-metadata = "3.2.3"
num-traits = "0.2.15"
solana-program = "~1.18.11"
spl-account-compression = { path="../../../solana-program-library/account-compression/programs/account-compression", features = ["cpi"] }
spl-associated-token-account = { version = ">= 1.1.3, < 3.0", features = ["no-entrypoint"] }
spl-token = { version = ">= 3.5.0, < 5.0", features = ["no-entrypoint"] }
mplx-staking-states = { path="../../../mplx-staking/program-states"}

[dev-dependencies]
async-trait = "0.1.71"
mpl-token-auth-rules = { path = "../../../mpl-token-auth-rules/programs/token-auth-rules/", features = ["no-entrypoint"] }
solana-program-test = "~1.18.11"
solana-sdk = "~1.18.11"
spl-concurrent-merkle-tree = { path = "../../../solana-program-library/libraries/concurrent-merkle-tree" }
spl-merkle-tree-reference = { path = "../../../solana-program-library/libraries/merkle-tree-reference" }
spl-noop = { path="../../../solana-program-library/account-compression/programs/noop", features = ["no-entrypoint"] }
